export const codeSnippets: Record<string, string> = {
  basics: [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropVue } from 'cropvue'",
    "import type { CropResult } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    'const result = ref<CropResult | null>(null)',
    '',
    'function onDone(cropResult: CropResult) {',
    '  result.value = cropResult',
    '  // cropResult contains: url, blob, width, height,',
    '  // originalWidth, originalHeight',
    '  console.log(`Cropped: ${cropResult.width}x${cropResult.height}`)',
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <CropVue',
    '    stencil="rectangle"',
    '    :output-quality="0.85"',
    '    :style="{',
    "      '--cropvue-crop-border-color': '#00d4ff',",
    "      '--cropvue-handle-color': '#00d4ff',",
    "      '--cropvue-editor-bg': '#111118',",
    '    }"',
    '    @done="onDone"',
    '  />',
    '',
    '  <div v-if="result">',
    '    <img :src="result.url" alt="Cropped" />',
    '    <p>{{ result.width }} &times; {{ result.height }}</p>',
    '  </div>',
    '<\/template>',
  ].join('\n'),

  avatar: [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropVue } from 'cropvue'",
    "import type { CropResult } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    'const avatar = ref<CropResult | null>(null)',
    '',
    'function onDone(result: CropResult) {',
    '  avatar.value = result',
    '  // Upload the cropped blob to your server:',
    '  // const formData = new FormData()',
    "  // formData.append('avatar', result.blob, 'avatar.webp')",
    "  // await fetch('/api/avatar', { method: 'POST', body: formData })",
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <CropVue',
    '    stencil="circle"',
    '    :aspect-ratio="1"',
    '    output-format="webp"',
    '    :output-quality="0.9"',
    '    @done="onDone"',
    '  >',
    '    <template #dropzone="{ open, isDragging }">',
    '      <div @click="open" class="avatar-dropzone">',
    "        {{ isDragging ? 'Drop image!' : 'Upload avatar' }}",
    '      </div>',
    '    <\/template>',
    '',
    '    <template #done="{ result, restart }">',
    '      <img :src="result.url" alt="Avatar" />',
    '      <p>{{ result.width }}&times;{{ result.height }} &middot; {{ result.blob.type }}</p>',
    '      <button @click="restart">Choose Different Photo</button>',
    '    <\/template>',
    '  </CropVue>',
    '<\/template>',
  ].join('\n'),

  'full-control': [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropVue } from 'cropvue'",
    "import type { CropResult } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    'const result = ref<CropResult | null>(null)',
    '',
    'function onDone(cropResult: CropResult) {',
    '  result.value = cropResult',
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <CropVue',
    '    stencil="rectangle"',
    '    :aspect-ratio="16 / 9"',
    '    output-format="jpeg"',
    '    :output-quality="0.8"',
    '    @done="onDone"',
    '  >',
    '    <!-- Custom file picker UI -->',
    '    <template #dropzone="{ open, isDragging }">',
    '      <div @click="open">',
    "        {{ isDragging ? 'Release to upload...' : 'Drop image or click to browse' }}",
    '      </div>',
    '    <\/template>',
    '',
    '    <!-- Custom toolbar with your own buttons -->',
    '    <template #toolbar="{ rotateLeft, rotateRight, flipX, flipY, zoomIn, zoomOut, reset }">',
    '      <div class="my-toolbar">',
    '        <button @click="rotateLeft">Rotate L</button>',
    '        <button @click="rotateRight">Rotate R</button>',
    '        <button @click="flipX">Flip X</button>',
    '        <button @click="flipY">Flip Y</button>',
    '        <button @click="zoomIn">Zoom +</button>',
    '        <button @click="zoomOut">Zoom -</button>',
    '        <button @click="reset">Reset</button>',
    '      </div>',
    '    <\/template>',
    '',
    '    <!-- Custom confirm/cancel buttons -->',
    '    <template #actions="{ confirm, cancel }">',
    '      <button @click="cancel">Discard</button>',
    '      <button @click="confirm">Export 16:9 JPEG</button>',
    '    <\/template>',
    '',
    '    <!-- Custom result display -->',
    '    <template #done="{ result, restart }">',
    '      <img :src="result.url" alt="Cropped" />',
    '      <p>{{ result.width }}&times;{{ result.height }} &middot; {{ result.blob.type }}</p>',
    '      <button @click="restart">Start Over</button>',
    '    <\/template>',
    '  </CropVue>',
    '<\/template>',
  ].join('\n'),

  'shape-shifter': [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropVue } from 'cropvue'",
    "import type { CropResult, StencilType, OutputFormat } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    '// All props are reactive — change them and the editor updates live',
    "const stencil = ref<StencilType>('rectangle')",
    'const aspectRatio = ref<number | null>(null)',
    "const format = ref<OutputFormat>('auto')",
    'const quality = ref(0.85)',
    'const result = ref<CropResult | null>(null)',
    '',
    'function onDone(cropResult: CropResult) {',
    '  result.value = cropResult',
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <!-- Controls to change props at runtime -->',
    '  <label>',
    '    Stencil:',
    "    <select v-model=\"stencil\">",
    '      <option value="rectangle">Rectangle</option>',
    '      <option value="circle">Circle</option>',
    '    </select>',
    '  </label>',
    '',
    '  <label>',
    '    Quality: {{ quality }}',
    '    <input type="range" v-model.number="quality" min="0.1" max="1" step="0.05" />',
    '  </label>',
    '',
    '  <!-- CropVue reacts to prop changes automatically -->',
    '  <CropVue',
    '    :stencil="stencil"',
    '    :aspect-ratio="aspectRatio"',
    '    :output-format="format"',
    '    :output-quality="quality"',
    '    @done="onDone"',
    '  />',
    '<\/template>',
  ].join('\n'),

  composable: [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropEditor, useCropper } from 'cropvue'",
    "import type { CropResult } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    '// Full programmatic control over the crop lifecycle',
    'const cropper = useCropper({',
    "  stencil: 'rectangle',",
    '  outputQuality: 0.85,',
    '})',
    '',
    'const result = ref<CropResult | null>(null)',
    '',
    'async function onFileSelect(e: Event) {',
    '  const input = e.target as HTMLInputElement',
    '  if (input.files?.[0]) {',
    '    await cropper.loadFile(input.files[0])',
    '  }',
    '}',
    '',
    'async function exportResult() {',
    "  result.value = await cropper.getResult({ format: 'webp', quality: 0.8 })",
    '  console.log(`Exported: ${result.value.width}x${result.value.height}`)',
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <input type="file" accept="image/*" @change="onFileSelect" />',
    '',
    '  <CropEditor',
    '    v-if="cropper.isReady.value"',
    '    :image="cropper.image.value"',
    '    :transform="cropper.transform.value"',
    '    :crop="cropper.crop.value"',
    '    @update:transform="t => cropper.transform.value = t"',
    '    @update:crop="c => cropper.crop.value = c"',
    '  />',
    '',
    '  <!-- Programmatic transform controls -->',
    '  <button @click="cropper.rotateLeft()">Rotate Left</button>',
    '  <button @click="cropper.flipX()">Flip X</button>',
    '  <button @click="cropper.zoomBy(0.1)">Zoom In</button>',
    '  <button @click="cropper.reset()">Reset</button>',
    '  <button @click="exportResult">Export</button>',
    '',
    '  <!-- Live transform state -->',
    '  <pre>{{ JSON.stringify(cropper.transform.value, null, 2) }}</pre>',
    '<\/template>',
  ].join('\n'),

  themes: [
    '<script setup lang="ts">',
    "import { CropVue } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    '// Theming is done entirely via CSS custom properties.',
    '// No code changes needed — just pass a :style binding.',
    'const midnightTheme = {',
    "  '--cropvue-editor-bg': '#0a1628',",
    "  '--cropvue-overlay-color': 'rgba(10, 22, 40, 0.7)',",
    "  '--cropvue-crop-border-color': '#22d3ee',",
    "  '--cropvue-grid-color': 'rgba(34, 211, 238, 0.3)',",
    "  '--cropvue-handle-color': '#22d3ee',",
    "  '--cropvue-toolbar-bg': '#0f1f38',",
    "  '--cropvue-toolbar-border-color': '#1a3050',",
    "  '--cropvue-toolbar-btn-color': '#7dd3fc',",
    "  '--cropvue-toolbar-btn-hover-bg': '#1a3050',",
    "  '--cropvue-btn-bg': '#0f1f38',",
    "  '--cropvue-btn-color': '#e0f2fe',",
    "  '--cropvue-btn-border-color': '#1a3050',",
    "  '--cropvue-btn-confirm-bg': '#0891b2',",
    "  '--cropvue-btn-confirm-color': '#fff',",
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <CropVue',
    '    stencil="circle"',
    '    :aspect-ratio="1"',
    '    :style="midnightTheme"',
    '  />',
    '<\/template>',
  ].join('\n'),

  'profile-editor': [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropVue } from 'cropvue'",
    "import type { CropResult } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    'const avatar = ref<CropResult | null>(null)',
    "const name = ref('Alex Johnson')",
    "const email = ref('alex@example.com')",
    "const bio = ref('Design-minded developer who loves clean UI.')",
    '',
    'function onAvatarDone(result: CropResult) {',
    '  avatar.value = result',
    '  // Upload to your server:',
    '  // const fd = new FormData()',
    "  // fd.append('avatar', result.blob, 'avatar.webp')",
    "  // await fetch('/api/profile/avatar', { method: 'POST', body: fd })",
    '}',
    '',
    'async function saveProfile() {',
    '  // Save profile data + avatar blob',
    "  console.log('Saving profile...', { name: name.value, email: email.value })",
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <div class="profile-card">',
    '    <div class="profile-grid">',
    '      <!-- Avatar column -->',
    '      <div class="avatar-col">',
    '        <CropVue',
    '          v-if="!avatar"',
    '          stencil="circle"',
    '          :aspect-ratio="1"',
    '          output-format="webp"',
    '          :output-quality="0.9"',
    '          @done="onAvatarDone"',
    '        >',
    '          <template #dropzone="{ open, isDragging }">',
    '            <div class="avatar-drop" @click="open">',
    "              {{ isDragging ? 'Drop photo' : 'Upload photo' }}",
    '            </div>',
    '          <\/template>',
    '        </CropVue>',
    '        <div v-else>',
    '          <img :src="avatar.url" alt="Avatar" class="avatar-preview" />',
    '          <button @click="avatar = null">Change photo</button>',
    '        </div>',
    '      </div>',
    '',
    '      <!-- Form column -->',
    '      <div class="form-col">',
    '        <label>Name</label>',
    '        <input v-model="name" type="text" />',
    '        <label>Email</label>',
    '        <input v-model="email" type="email" />',
    '        <label>Bio</label>',
    '        <textarea v-model="bio" rows="3" />',
    '      </div>',
    '    </div>',
    '',
    '    <div class="actions">',
    '      <button @click="saveProfile">Save Profile</button>',
    '    </div>',
    '  </div>',
    '<\/template>',
  ].join('\n'),

  'post-composer': [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropVue } from 'cropvue'",
    "import type { CropResult } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    'const cover = ref<CropResult | null>(null)',
    "const title = ref('')",
    "const body = ref('')",
    "const tags = ref(['Design', 'Vue', 'Tutorial'])",
    '',
    'function onCoverDone(result: CropResult) {',
    '  cover.value = result',
    '}',
    '',
    'function removeCover() {',
    '  cover.value = null',
    '}',
    '',
    'async function publish() {',
    '  const formData = new FormData()',
    "  formData.append('title', title.value)",
    "  formData.append('body', body.value)",
    '  if (cover.value) {',
    "    formData.append('cover', cover.value.blob, 'cover.jpg')",
    '  }',
    "  // await fetch('/api/posts', { method: 'POST', body: formData })",
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <div class="post-card">',
    '    <!-- Cover image area -->',
    '    <div class="cover-area">',
    '      <CropVue',
    '        v-if="!cover"',
    '        stencil="rectangle"',
    '        :aspect-ratio="16 / 9"',
    '        output-format="jpeg"',
    '        :output-quality="0.85"',
    '        @done="onCoverDone"',
    '      >',
    '        <template #dropzone="{ open, isDragging }">',
    '          <div class="cover-drop" @click="open">',
    "            {{ isDragging ? 'Drop to set cover' : 'Add cover image' }}",
    '          </div>',
    '        <\/template>',
    '      </CropVue>',
    '      <div v-else class="cover-preview">',
    '        <img :src="cover.url" alt="Cover" />',
    '        <button class="remove-btn" @click="removeCover">&times;</button>',
    '      </div>',
    '    </div>',
    '',
    '    <!-- Post content -->',
    '    <input v-model="title" placeholder="Post title..." class="title-input" />',
    '    <textarea v-model="body" placeholder="Write your post..." rows="4" />',
    '',
    '    <!-- Tags -->',
    '    <div class="tags">',
    '      <span v-for="tag in tags" :key="tag" class="tag">{{ tag }}</span>',
    '    </div>',
    '',
    '    <button @click="publish">Publish</button>',
    '  </div>',
    '<\/template>',
  ].join('\n'),

  'product-gallery': [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropVue } from 'cropvue'",
    "import type { CropResult } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    '// 4 image slots: 1 hero + 3 thumbnails',
    'const images = ref<(CropResult | null)[]>([null, null, null, null])',
    'const activeSlot = ref<number | null>(null)',
    'const showCropper = ref(false)',
    '',
    'function openSlot(index: number) {',
    '  activeSlot.value = index',
    '  showCropper.value = true',
    '}',
    '',
    'function onCrop(result: CropResult) {',
    '  if (activeSlot.value !== null) {',
    '    const imgs = [...images.value]',
    '    imgs[activeSlot.value] = result',
    '    images.value = imgs',
    '  }',
    '  showCropper.value = false',
    '  activeSlot.value = null',
    '}',
    '',
    'function removeImage(index: number) {',
    '  const imgs = [...images.value]',
    '  imgs[index] = null',
    '  images.value = imgs',
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <div class="product-card">',
    '    <!-- Image grid: hero + thumbnails -->',
    '    <div class="image-grid">',
    '      <div class="hero-slot" @click="!images[0] && openSlot(0)">',
    '        <img v-if="images[0]" :src="images[0].url" alt="Main" />',
    '        <span v-else>+ Main photo</span>',
    '      </div>',
    '      <div class="thumb-row">',
    '        <div',
    '          v-for="i in [1, 2, 3]"',
    '          :key="i"',
    '          class="thumb-slot"',
    '          @click="!images[i] && openSlot(i)"',
    '        >',
    '          <img v-if="images[i]" :src="images[i]!.url" alt="Thumb" />',
    '          <span v-else>+</span>',
    '        </div>',
    '      </div>',
    '    </div>',
    '',
    '    <!-- Shared CropVue instance - shows when a slot is clicked -->',
    '    <CropVue',
    '      v-if="showCropper"',
    '      stencil="rectangle"',
    '      :aspect-ratio="1"',
    '      output-format="webp"',
    '      :output-quality="0.9"',
    '      @done="onCrop"',
    '    />',
    '',
    '    <!-- Product info -->',
    '    <h3>Artisan Ceramic Vase</h3>',
    '    <p class="price">$89.00</p>',
    '    <p>Hand-thrown stoneware vase with reactive glaze finish.</p>',
    '    <button class="add-to-cart">Add to Cart</button>',
    '  </div>',
    '<\/template>',
  ].join('\n'),

  standalone: [
    '<script setup lang="ts">',
    "import { ref } from 'vue'",
    "import { CropDropzone, CropToolbar, CropVue } from 'cropvue'",
    "import type { TransformState } from 'cropvue'",
    "import 'cropvue/styles'",
    '',
    '// --- Standalone Dropzone ---',
    'const files = ref<File[]>([])',
    'function onFiles(newFiles: File[]) {',
    '  files.value.push(...newFiles)',
    '  console.log(`Received ${newFiles.length} file(s)`)',
    '}',
    '',
    '// --- Standalone Toolbar ---',
    'const transform = ref<TransformState>({',
    '  x: 0, y: 0, scale: 1, rotation: 0,',
    '  flipX: false, flipY: false,',
    '})',
    '',
    'function onRotateLeft() {',
    '  transform.value = { ...transform.value, rotation: transform.value.rotation - 90 }',
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <!-- Use CropDropzone independently as a file picker -->',
    '  <CropDropzone @files="onFiles">',
    '    <template #default="{ open, isDragging }">',
    "      <div @click=\"open\">{{ isDragging ? 'Drop!' : 'Browse files' }}</div>",
    '    <\/template>',
    '  </CropDropzone>',
    '',
    '  <!-- Use CropToolbar independently to control transforms -->',
    '  <CropToolbar',
    '    :transform="transform"',
    '    @rotate-left="onRotateLeft"',
    '    @rotate-right="() => { /* ... */ }"',
    '    @flip-x="() => { /* ... */ }"',
    '    @reset="() => { /* ... */ }"',
    '  />',
    '',
    '  <!-- Load an image directly from a URL -->',
    '  <CropVue src="https://picsum.photos/id/1040/800/600" stencil="rectangle" />',
    '<\/template>',
  ].join('\n'),
}
