export const codeSnippets: Record<string, string> = {
  basics: [
    '<template>',
    '  <CropVue',
    '    stencil="rectangle"',
    '    :output-quality="0.85"',
    '    :style="{',
    "      '--cropvue-crop-border-color': '#00d4ff',",
    "      '--cropvue-handle-color': '#00d4ff',",
    "      '--cropvue-editor-bg': '#111118',",
    '    }"',
    '    @done="onDone"',
    '  />',
    '<\/template>',
  ].join('\n'),

  avatar: [
    '<template>',
    '  <CropVue',
    '    stencil="circle"',
    '    :aspect-ratio="1"',
    '    output-format="webp"',
    '    @done="onDone"',
    '  >',
    '    <template #dropzone="{ open, isDragging }">',
    '      <div @click="open">',
    "        {{ isDragging ? 'Drop!' : 'Upload avatar' }}",
    '      </div>',
    '    <\/template>',
    '',
    '    <template #done="{ result, restart }">',
    '      <img :src="result.url" alt="Avatar" />',
    '      <button @click="restart">Choose Another</button>',
    '    <\/template>',
    '  </CropVue>',
    '<\/template>',
  ].join('\n'),

  'full-control': [
    '<template>',
    '  <CropVue',
    '    stencil="rectangle"',
    '    :aspect-ratio="16 / 9"',
    '    output-format="jpeg"',
    '    :output-quality="0.8"',
    '    @done="onDone"',
    '  >',
    '    <template #dropzone="{ open, isDragging }">',
    '      <div @click="open">Drop or click</div>',
    '    <\/template>',
    '',
    '    <template #toolbar="{ rotateLeft, flipX, zoomIn, reset }">',
    '      <button @click="rotateLeft">Rotate</button>',
    '      <button @click="flipX">Flip</button>',
    '      <button @click="zoomIn">Zoom</button>',
    '      <button @click="reset">Reset</button>',
    '    <\/template>',
    '',
    '    <template #actions="{ confirm, cancel }">',
    '      <button @click="cancel">Discard</button>',
    '      <button @click="confirm">Export</button>',
    '    <\/template>',
    '',
    '    <template #done="{ result, restart }">',
    '      <img :src="result.url" />',
    '      <button @click="restart">Start Over</button>',
    '    <\/template>',
    '  </CropVue>',
    '<\/template>',
  ].join('\n'),

  'shape-shifter': [
    '<script setup>',
    "import { ref } from 'vue'",
    '',
    "const stencil = ref('rectangle')",
    'const aspectRatio = ref(null)',
    "const format = ref('auto')",
    'const quality = ref(0.85)',
    '<\/script>',
    '',
    '<template>',
    '  <CropVue',
    '    :stencil="stencil"',
    '    :aspect-ratio="aspectRatio"',
    '    :output-format="format"',
    '    :output-quality="quality"',
    '    @done="onDone"',
    '  />',
    '<\/template>',
  ].join('\n'),

  composable: [
    '<script setup>',
    "import { CropEditor, useCropper } from 'cropvue'",
    '',
    'const cropper = useCropper({',
    "  stencil: 'rectangle',",
    '  outputQuality: 0.85,',
    '})',
    '',
    'async function exportResult() {',
    '  const result = await cropper.getResult({',
    "    format: 'webp',",
    '    quality: 0.8,',
    '  })',
    '}',
    '<\/script>',
    '',
    '<template>',
    '  <input type="file" @change="cropper.loadFile($event.target.files[0])" />',
    '',
    '  <CropEditor',
    '    v-if="cropper.isReady.value"',
    '    :image="cropper.image.value"',
    '    :transform="cropper.transform.value"',
    '    :crop="cropper.crop.value"',
    '    @update:transform="t => cropper.transform.value = t"',
    '    @update:crop="c => cropper.crop.value = c"',
    '  />',
    '<\/template>',
  ].join('\n'),

  themes: [
    '<template>',
    '  <!-- Theme via CSS custom properties — zero code changes -->',
    '  <CropVue',
    '    stencil="circle"',
    '    :aspect-ratio="1"',
    '    :style="{',
    "      '--cropvue-editor-bg': '#0a1628',",
    "      '--cropvue-crop-border-color': '#22d3ee',",
    "      '--cropvue-handle-color': '#22d3ee',",
    "      '--cropvue-overlay-color': 'rgba(10, 22, 40, 0.7)',",
    "      '--cropvue-toolbar-bg': '#0f1f38',",
    "      '--cropvue-btn-confirm-bg': '#0891b2',",
    '    }"',
    '  />',
    '<\/template>',
  ].join('\n'),

  standalone: [
    '<script setup>',
    "import { ref } from 'vue'",
    "import { CropDropzone, CropToolbar, CropVue } from 'cropvue'",
    '',
    'const files = ref([])',
    'const transform = ref({',
    '  x: 0, y: 0, scale: 1, rotation: 0,',
    '  flipX: false, flipY: false,',
    '})',
    '<\/script>',
    '',
    '<template>',
    '  <!-- Standalone dropzone -->',
    '  <CropDropzone @files="f => files.push(...f)">',
    '    <template #default="{ open, isDragging }">',
    "      <div @click=\"open\">{{ isDragging ? 'Drop!' : 'Browse' }}</div>",
    '    <\/template>',
    '  </CropDropzone>',
    '',
    '  <!-- Standalone toolbar -->',
    '  <CropToolbar',
    '    :transform="transform"',
    '    @rotate-left="onRotateLeft"',
    '    @flip-x="onFlipX"',
    '  />',
    '',
    '  <!-- URL loading -->',
    '  <CropVue src="https://example.com/photo.jpg" />',
    '<\/template>',
  ].join('\n'),
}
